# Exported from Render on 2024-05-30T08:13:10Z
services:
  - type: web
    name: loggy-blog
    runtime: docker
    repo: https://github.com/micheltsiresitsilavo/loggy-blog
    plan: free
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
          published: ${HTTP_PORT:-80}
          protocol: tcp
      # HTTPS
      - target: 443
          published: ${HTTPS_PORT:-443}
          protocol: tcp
      # HTTP/3
      - target: 443
          published: ${HTTP3_PORT:-443}
          protocol: udp      
    envVars:
      - key: DB_USERNAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_CONNECTION
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_NAME
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        sync: false
    region: oregon
    healthCheckPath: /status
    dockerContext: .
    dockerfilePath: ./Dockerfile
volumes:
  caddy_data:
  caddy_config: